import { DashboardLayout } from '@/components/dashboard/DashboardLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useAuth } from '@/contexts/AuthContext';
import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Tables } from '@/integrations/supabase/types';
import { useNavigate } from 'react-router-dom';
import { CreditCard, Eye, EyeOff, Send, ArrowDownLeft, ArrowUpRight, Copy, Plus, TrendingUp, DollarSign, Wallet } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Label } from '@/components/ui/label';

const ACCOUNT_TYPE_CONFIG: Record<string, { icon: any; color: string; bgColor: string }> = {
  checking: { icon: CreditCard, color: 'text-blue-500', bgColor: 'bg-blue-500/10' },
  savings: { icon: Wallet, color: 'text-green-500', bgColor: 'bg-green-500/10' },
  crypto: { icon: TrendingUp, color: 'text-orange-500', bgColor: 'bg-orange-500/10' },
  investment: { icon: DollarSign, color: 'text-purple-500', bgColor: 'bg-purple-500/10' },
};

export default function Accounts() {
  const { session } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [accounts, setAccounts] = useState<Tables<'accounts'>[]>([]);
  const [recentTx, setRecentTx] = useState<Tables<'transactions'>[]>([]);
  const [loading, setLoading] = useState(true);
  const [showBalances, setShowBalances] = useState(true);
  const [openNewAccount, setOpenNewAccount] = useState(false);
  const [newAccountType, setNewAccountType] = useState('');
  const [creating, setCreating] = useState(false);

  const loadData = async () => {
    if (!session?.user?.id) return;
    try {
      const [acctRes, txRes] = await Promise.all([
        supabase.from('accounts').select('*').eq('user_id', session.user.id).order('created_at', { ascending: false }),
        supabase.from('transactions').select('*').eq('user_id', session.user.id).order('created_at', { ascending: false }).limit(5),
      ]);
      if (acctRes.error) throw acctRes.error;
      setAccounts(acctRes.data || []);
      setRecentTx(txRes.data || []);
    } catch (error) {
      console.error('Error loading accounts:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { loadData(); }, [session?.user?.id]);

  const totalBalance = accounts.reduce((sum, a) => sum + Number(a.balance), 0);

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    toast({ title: 'Copied', description: `${label} copied to clipboard` });
  };

  const formatBalance = (balance: number) => {
    if (!showBalances) return '••••••';
    return `$${balance.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
  };

  const handleCreateAccount = async () => {
    if (!newAccountType || !session?.user?.id) return;
    const existing = accounts.find(a => a.account_type === newAccountType);
    if (existing) {
      toast({ title: 'Already exists', description: `You already have a ${newAccountType} account.`, variant: 'destructive' });
      return;
    }
    setCreating(true);
    const { error } = await supabase.from('accounts').insert({
      user_id: session.user.id,
      account_type: newAccountType as any,
      account_number: '', // auto-generated by trigger
    });
    if (error) {
      toast({ title: 'Error', description: error.message, variant: 'destructive' });
    } else {
      toast({ title: 'Account created!', description: `Your new ${newAccountType} account is now active.` });
      setOpenNewAccount(false);
      setNewAccountType('');
      loadData();
    }
    setCreating(false);
  };

  const existingTypes = accounts.map(a => a.account_type);
  const availableTypes = ['checking', 'savings', 'crypto', 'investment'].filter(t => !existingTypes.includes(t as any));

  return (
    <DashboardLayout title="Accounts" description="Manage your financial accounts">
      {loading ? (
        <div className="text-center text-muted-foreground py-12">Loading accounts...</div>
      ) : (
        <div className="space-y-6">
          {/* Total Balance + Actions */}
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardDescription>Total Balance</CardDescription>
                  <CardTitle className="text-4xl mt-1">{formatBalance(totalBalance)}</CardTitle>
                </div>
                <Button variant="ghost" size="icon" onClick={() => setShowBalances(!showBalances)}>
                  {showBalances ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex gap-3">
                <Button size="sm" onClick={() => navigate('/dashboard/transfers')}>
                  <Send className="mr-2 h-4 w-4" /> Transfer
                </Button>
                {availableTypes.length > 0 && (
                  <Dialog open={openNewAccount} onOpenChange={setOpenNewAccount}>
                    <DialogTrigger asChild>
                      <Button size="sm" variant="outline">
                        <Plus className="mr-2 h-4 w-4" /> Open New Account
                      </Button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>Open a New Account</DialogTitle>
                        <DialogDescription>Choose an account type to open. Each type offers different features.</DialogDescription>
                      </DialogHeader>
                      <div className="space-y-4 pt-4">
                        <div className="space-y-2">
                          <Label>Account Type</Label>
                          <Select value={newAccountType} onValueChange={setNewAccountType}>
                            <SelectTrigger><SelectValue placeholder="Select account type" /></SelectTrigger>
                            <SelectContent>
                              {availableTypes.map(t => (
                                <SelectItem key={t} value={t}>
                                  <span className="capitalize">{t}</span>
                                  <span className="text-xs text-muted-foreground ml-2">
                                    {t === 'checking' && '— Everyday transactions'}
                                    {t === 'savings' && '— Earn interest on deposits'}
                                    {t === 'crypto' && '— Buy & sell cryptocurrency'}
                                    {t === 'investment' && '— Stocks, bonds & ETFs'}
                                  </span>
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                        <Button onClick={handleCreateAccount} disabled={!newAccountType || creating} className="w-full">
                          {creating ? 'Creating...' : 'Open Account'}
                        </Button>
                      </div>
                    </DialogContent>
                  </Dialog>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Account Cards */}
          {accounts.length === 0 ? (
            <Card>
              <CardContent className="pt-6 text-center text-muted-foreground">
                No accounts yet. Open your first account above!
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4 md:grid-cols-2">
              {accounts.map((account) => {
                const config = ACCOUNT_TYPE_CONFIG[account.account_type] || ACCOUNT_TYPE_CONFIG.checking;
                const Icon = config.icon;
                return (
                  <Card key={account.id} className="relative overflow-hidden">
                    <div className={`absolute top-0 left-0 right-0 h-1 ${
                      account.account_type === 'checking' ? 'bg-blue-500' :
                      account.account_type === 'savings' ? 'bg-green-500' :
                      account.account_type === 'crypto' ? 'bg-orange-500' : 'bg-purple-500'
                    }`} />
                    <CardHeader>
                      <div className="flex justify-between items-start">
                        <div className="flex items-center gap-3">
                          <div className={`p-2 rounded-lg ${config.bgColor}`}>
                            <Icon className={`h-5 w-5 ${config.color}`} />
                          </div>
                          <div>
                            <CardTitle className="text-lg capitalize">{account.account_type} Account</CardTitle>
                            <div className="space-y-1 mt-1">
                              <div className="flex items-center gap-2">
                                <span className="text-xs text-muted-foreground">Acct:</span>
                                <span className="font-mono text-xs">{account.account_number}</span>
                                <button onClick={() => copyToClipboard(account.account_number, 'Account number')} className="text-muted-foreground hover:text-foreground">
                                  <Copy className="h-3 w-3" />
                                </button>
                              </div>
                              {(account as any).routing_number && (
                                <div className="flex items-center gap-2">
                                  <span className="text-xs text-muted-foreground">Routing:</span>
                                  <span className="font-mono text-xs">{(account as any).routing_number}</span>
                                  <button onClick={() => copyToClipboard((account as any).routing_number, 'Routing number')} className="text-muted-foreground hover:text-foreground">
                                    <Copy className="h-3 w-3" />
                                  </button>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                        <Badge variant={account.status === 'active' ? 'default' : 'destructive'}>
                          {account.status}
                        </Badge>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-4">
                        <div>
                          <p className="text-sm text-muted-foreground">Available Balance</p>
                          <p className="text-3xl font-bold">{formatBalance(Number(account.balance))}</p>
                        </div>
                        <div className="flex items-center justify-between text-sm text-muted-foreground">
                          <span>Currency: {account.currency}</span>
                          <span>Opened: {new Date(account.created_at).toLocaleDateString()}</span>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}

          {/* Recent Transactions */}
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>Recent Transactions</CardTitle>
                <Button variant="ghost" size="sm" onClick={() => navigate('/dashboard/transfers')}>
                  View All
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              {recentTx.length === 0 ? (
                <p className="text-center text-muted-foreground py-4">No transactions yet</p>
              ) : (
                <div className="space-y-3">
                  {recentTx.map((tx) => {
                    const isOutgoing = tx.type === 'withdrawal' || tx.type === 'transfer' || tx.type === 'crypto_buy';
                    return (
                      <div key={tx.id} className="flex items-center justify-between p-3 rounded-lg border">
                        <div className="flex items-center gap-3">
                          {isOutgoing ? (
                            <ArrowUpRight className="h-4 w-4 text-destructive" />
                          ) : (
                            <ArrowDownLeft className="h-4 w-4 text-green-500" />
                          )}
                          <div>
                            <p className="text-sm font-medium capitalize">{tx.type.replace('_', ' ')}</p>
                            <p className="text-xs text-muted-foreground">{new Date(tx.created_at).toLocaleDateString()}</p>
                          </div>
                        </div>
                        <span className={`font-semibold ${isOutgoing ? 'text-destructive' : 'text-green-500'}`}>
                          {isOutgoing ? '-' : '+'}${Number(tx.amount).toLocaleString('en-US', { minimumFractionDigits: 2 })}
                        </span>
                      </div>
                    );
                  })}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      )}
    </DashboardLayout>
  );
}
